language: python
services:
  - docker

before_install: 
  - docker build -t zseifert/vote_app myob2/.
  - docker run -d -p 8888:8888 --name testapp zseifert/vote_app 
  - docker ps 


script:
   - docker exec -it testapp pytest -v 
