language: python
services:
  - docker

before_install: 
  - python3 update_json.py myob2/build_info.json "$TRAVIS_COMMIT"
  - docker build -t $DOCKER_USERNAME/vote_app:travis myob2/.
  - docker run -d -p 8888:8888 --name testapp zseifert/vote_app 
  - docker ps -a


script:
   - docker exec -it testapp pytest -v 

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
